---
# tasks file for mariadb
- name: install mariadb server package for CentOS
  dnf:
   name: mariadb-server
   state: latest
   update_cache: yes
  when: ansible_distribution == "CentOS"

- name: install mariadb server for Ubuntu
  apt:
   name: mariadb-server
   state: latest
   update_cache: yes
  when: ansible_distribution == "Ubuntu"
