---
# Install Kibana on Ubuntu

  - name: Install Kibana on Ubuntu
    apt:
      name: kibana
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Reload Daemon for Kibana on Ubuntu
    systemd: daemon_reload=yes
    when: ansible_distribution == "Ubuntu"

  - name: Enable Kibana on Ubuntu
    systemd:
      name: kibana
      enabled: yes
    when: ansible_distribution == "Ubuntu"

# Install Kibana on CentOS

  - name: Install Kibana on CentOS
    yum:
      name: kibana
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Reload Daemon for Kibana on CentOS
    systemd: daemon_reload=yes
    when: ansible_distribution == "CentOS"

  - name: Enable Kibana on CentOS
    systemd:
      name: kibana
      enabled: yes
    when: ansible_distribution == "CentOS"
